- include/uvwasi.h
- src/uvwasi.c
This commit adds a `uvwasi_embedder_remap_fd()` API which allows the embedder (for example, Node.js) to change out the underlying host file descriptor of a WASI file descriptor.
One use case for this is allowing the stdio streams of individual WASI instances to be changed. I tested with Node.js, and it seems to work as intended.
This is intended as a fix for https://github.com/cjihrig/uvwasi/issues/13. I decided not to add it as an option to `uvwasi_init()`.
cc: @danbev @tniessen @guybedford
> support remapping host fds of sandbox

- src/fd_table.c
> add missing #include

- app.c
- src/uvwasi.c
This commit fixes a few compiler warnings. It also adds some Windows `#ifdef` logic. The resulting Windows code does not work, but it didn't work before this either (the goal is to get it compiling).
Fixes: https://github.com/cjihrig/uvwasi/issues/26 (I hope)
Green CI: https://github.com/cjihrig/uvwasi/commit/5df92f87e3259a7c941a83fd0c4449e230127780/checks?check_suite_id=262439257 (apologies if I'm doing something wrong with the GitHub CI, this is my first exposure to it)
cc: @gengjiawen
> fix a few compiler warnings

- CMakeLists.txt
This commit adds the message command to CMakeLists.txt to output a
summary of some useful information. The following will be displayed when
with this addition:
```console
$ cd build && cmake ..
-- summary of build options:
Install prefix:  /usr/local
Target system:   Darwin
Compiler:
C compiler:    /work/ccache/ccache
CFLAGS:         -g -I/work/nodejs/libuv-build/include
Libuv version:   1.32.0
Libuv lib:       /work/wasm/uvwasi/build/_deps/libuv-build
-- Configuring done
-- Generating done
-- Build files have been written to: //work/wasm/uvwasi/build
```
> add cmake configuration summary

- CMakeLists.txt
- src/uvwasi.c
libuv 1.33.0 also ships `uv_random()`, meaning that the `__wasi_random_get()` implementation is now available.
> update to libuv 1.33.0

- test/test-einval-input-validation.c
- test/test-path-create-remove-directory.c
This commit adds tests to all of the syscall APIs to verify that they return `__WASI_EINVAL` when a `NULL` pointer is passed in.
(Covered lines jumps from 33.4% to 45.8%)
> add input validation tests

- src/uvwasi.c
- test/test-basic-file-io.c
- test/test-ebadf-input-validation.c
- test/test-enotsup-apis.c
- test/test-environ-get.c
- test/test-random-get.c
This PR bumps coverage from 64.2% to 74.7%. It also uncovered a bug in `__wasi_path_filestat_get()` which will need to be fixed.
> add more code coverage

- src/uv_mapping.c
On at least some AIX machines, `ENOTEMPTY` and `EEXIST` are equivalent. This prevents a `switch...case` statement from compiling. This commit works around the issue.
> fix aix compilation error

- include/wasi_types.h
The values of the constants were originally taken from the WASI API documentation. This was a mistake on my part. This commit updates the constants based on the actual values used in wasi-libc.
Refs: https://github.com/CraneStation/wasi-libc/blob/ec3ee5e98541a89b9db016005fa0e9f0287fd755/libc-bottom-half/headers/public/wasi/core.h
> sync constants from wasi-libc

- include/wasi_types.h
- src/uvwasi.c
This PR adds non-Windows support for the clocks `UVWASI_CLOCK_PROCESS_CPUTIME_ID` and `UVWASI_CLOCK_THREAD_CPUTIME_ID` in `__wasi_clock_time_get()`.
The first commit can be ignored - it is https://github.com/cjihrig/uvwasi/pull/47.
> support missing clocks in __wasi_clock_time_get()

- src/uvwasi.c
Skip allocating memory in `uvwasi_init()` for allocations of size zero. On platforms that return `NULL` for these allocations (like AIX), the result was being confused for an `ENOMEM`.
> handle zero-sized allocations in uvwasi_init()

- app.c
- include/fd_table.h
- include/uvwasi.h
- src/fd_table.c
- src/uvwasi.c
- src/uvwasi_alloc.h
- test/test-args-get.c
- test/test-basic-file-io.c
- test/test-ebadf-input-validation.c
- test/test-environ-get.c
- test/test-fd-prestat-dir-name.c
- test/test-path-create-remove-directory.c
- test/test-random-get.c
This is a good idea for libraries in general, and helps with tracking
memory allocated by uvwasi in Node.js.
The allocator struct format is identical to the one used by nghttp2
and related libraries, which makes things a bit easier because we’ve
added generic support for that format in the QUIC repo.
> add custom allocator option

- include/fd_table.h
- src/fd_table.c
- src/uvwasi.c
This would usually waste memory otherwise. Instead, store the
mapped path and the realpath in a separate buffer per-entry.
As a drive-by fix, this also destroys the per-fd mutexes now
in `uvwasi_fd_table_free()`.
Before this, some functions such as `uvwasi_path_open()` could
crash, because they acquired a reference to a fd table entry
using `uvwasi_fd_table_get()` and continued to use the result
after calling `uvwasi_fd_table_insert_fd()`; however, the latter
could `realloc()` the fd table, potentially invalidating the
earlier return value of `uvwasi_fd_table_get()`.
Since the previous commit introduced a per-fd allocation anyway,
this modifies the code to allocate the table entry itself as part
of that allocation. This ensures referential integrity for
the table entry.
(Aside -- I’m not …
> fd table refactoring

- README.md
- app.c
- include/uvwasi.h
- include/wasi_types.h
Fixes: https://github.com/cjihrig/uvwasi/issues/23
> update to snapshot_1

- src/fd_table.c
- test/test-multiple-wasi-destroys.c
This commit ensures that multiple calls to `uvwasi_destroy()` are possible. Prior to this commit, subsequent calls to destroy() would abort because the file table's rwlock was incorrectly being destroyed multiple times.
> support multiple calls to uvwasi_destroy()

- CMakeLists.txt
- src/uvwasi.c
Defined `_GNU_SOURCE` to suppress warnings
thrown during node build from scratch.
Refs: https://github.com/nodejs/node/pull/31139
> src: suppress warnings in uvwasi.c

- src/uvwasi.c
Thanks to work done by @gengjiawen (https://github.com/nodejs/node/pull/31153) we're now running Node.js tests as GitHub actions and this appears to be annotating pull requests in core with build warnings from unchanged files, one of which is from [`deps/uvwasi/src/uvwasi.c`](https://github.com/nodejs/node/pull/31300/checks?check_run_id=383837881#step:6:54):
The full warning, from https://github.com/cjihrig/uvwasi/runs/362355578#step:5:383:
```console
##[warning]D:\a\uvwasi\uvwasi\src\uvwasi.c(225,16): warning C4013: '_lseeki64' undefined; assuming extern returning int [D:\a\uvwasi\uvwasi\uvwasi_a.vcxproj]
```
> fix '_lseeki64' undefined compiler warning

- src/uvwasi.c
This commit includes the following improvements:
- Better path resolution. WASI applications should have
no knowledge of the underlying host file system. Prior
to this commit, those details were exposed in a few
edge cases.
- Added support for reading and following symlinks.
Prior to this commit, that worked, but the content of
the symlinks were based on the host syste, which was
wrong.
- Writing symlinks works on non-Windows platforms now.
- Remove use of strtok().
The CI seems to be passing. More importantly, I successfully ran these changes through the Node.js CI (https://ci.nodejs.org/job/node-test-commit/34852/).
> refactor path resolution

- src/uvwasi.c
https://github.com/cjihrig/uvwasi/commit/20fd9e2 was accidentally reverted in https://github.com/cjihrig/uvwasi/pull/73. This commit relands it.
> reland "fix '_lseeki64' undefined compiler warning"

- include/fd_table.h
- src/fd_table.c
- src/uvwasi.c
This commit moves the file descriptor renumbering operation into the file descriptor table code since it depends on performing several fd table operations, and uses its internals. The previous implementation was broken anyway.
CI seems fine. [Node CI](https://ci.nodejs.org/job/node-test-commit/34957/) with a [new test](https://github.com/cjihrig/node-1/commit/7002f80c0744f2a43887d62b9251d46da4cafd8f) for this functionality seems fine too.
> move fd renumbering into the fd table

- src/fd_table.c
- src/uvwasi.c
Some functions acquire mutexes for multiple file descriptors.
This commit ensures that the mutexes are released in the
reverse order that they are acquired.
Refs: https://github.com/nodejs/node/pull/31432#pullrequestreview-345604137
> unlock all fd mutexes in reverse order

- include/fd_table.h
- src/fd_table.c
- src/uvwasi.c
`uvwasi_path_rename()`, `uvwasi_path_link()`, `uvwasi_path_open()`, and `uvwasi_fd_renumber()` operate on multiple file descriptors. `uvwasi_fd_renumber()` has been updated prior to this commit, and is not relevant here. The other three functions would perform
the following locking operations:
- lock the file table
- acquire a file descriptor mutex
- unlock the file table
- lock the file table again
- acquire another file descriptor mutex
- unlock the file table
- unlock the two mutexes
Attempting to acquire the second mutex introduced the possibility of deadlock because another thread could attempt to acquire the first mutex while holding the file table lock.
This commit ensures that multiple mutexes are either:
- acquired in a single lock of the file table
- or, only acquired after …
> prevent locking fd table while holding a mutex

- include/fd_table.h
- src/fd_table.c
- src/uvwasi.c
This depends on https://github.com/cjihrig/uvwasi/pull/90 (the first commit in this PR).
`uvwasi_fd_close()` performed the following operations:
- lock the file descriptor mutex
- close the file
- release the file descriptor mutex
- call the file table's `remove()` function
Once the fd's mutex is released, another thread could acquire it
before the fd is removed from the file table. If this happens,
`remove()` could destroy a held mutex.
This commit updates `uvwasi_fd_close()` to perform the entire
sequence while holding the file table's lock, preventing new
acquisitions of the fd's mutex.
Fixes: https://github.com/cjihrig/uvwasi/issues/88
> prevent race conditions with uvwasi_fd_close()

- src/uv_mapping.c
`uv_fs_fstat()` fails on TTYs on Windows. This commit updates `uvwasi__get_filetype_by_fd()` to detect this case and map the fd to the WASI character device type.
Refs: https://github.com/nodejs/node/issues/31461
> allow windows to detect tty types

- README.md
This PR adds some basic build instructions for those who may not be familiar with CMake.
Happy to move these to another location in the repo if preferred!
cc @cjihrig
> docs: add build instructions

- src/clocks.c
`clocks.c` was missing the associated header file, so it caused errors in Electron like the following:
This PR rectifies that by adding the missing header.
cc @cjihrig
> src: add missing clocks header include

- src/uvwasi.c
The API posix_fadvise is not supported on IBMi PASE
> ibmi: remove unsupported API posix_fadvise on IBMi PASE

- README.md
- include/fd_table.h
- include/uvwasi.h
- src/fd_table.c
- src/uvwasi.c
- test/test-args-get.c
- test/test-basic-file-io.c
- test/test-ebadf-input-validation.c
- test/test-environ-get.c
- test/test-fd-prestat-dir-name.c
- test/test-multiple-wasi-destroys.c
- test/test-path-create-remove-directory.c
- test/test-random-get.c
This PR adds options to `uvwasi_init()` to allow setting the stdio file descriptors. This will allow embedders like Node.js to run multiple WASI applications in the same process without sharing stdio.
Unfortunately, Windows doesn't seem to like the use of the names `stdin`, `stdout`, and `stderr` as struct members, which is why I went with `in`, `out`, and `err`.
> make stdio configurable

- src/clocks.c
The API clock_getres with attribute API CLOCK_THREAD_CPUTIME_ID
is not supported on IBM i PASE.
> ibmi: skip calling CLOCK_THREAD_CPUTIME_ID on IBMi

- CMakeLists.txt
- src/debug.h
- src/uvwasi.c
Fixes: https://github.com/cjihrig/uvwasi/issues/110
> introduce debug macro

- src/path_resolver.c
- src/path_resolver.h
- src/uvwasi.c
- test/test-path-resolution.c
This commit removes `PATH_MAX_BYTES` and all of the code that
relies on it. All paths are now dynamically allocated.
Fixes: https://github.com/cjihrig/uvwasi/issues/114
> remove path length restrictions

- CMakeLists.txt
- src/poll_oneoff.c
- src/poll_oneoff.h
- src/uvwasi.c
- test/test-einval-input-validation.c
- test/test-enotsup-apis.c
The implementation is currently limited by what `uv_poll_t`'s support.
Fixes: https://github.com/cjihrig/uvwasi/issues/12
Tested in the [context of Node.js](https://github.com/cjihrig/node/commit/638a361669d4208258000296e4333921a734db45) with [a CI run](https://ci.nodejs.org/job/node-test-commit/38231/).
> src: add initial poll_oneoff() implementation

- CMakeLists.txt
This commit conditionally creates the test targets if uvwasi
is the root project. This is to prevent collisions with targets
from projects that embed uvwasi.
Refs: https://github.com/cjihrig/uvwasi/issues/118
I tested this by adding a `check` target to wasm3. Prior to this change it failed. With this change, it succeeded.
> build: conditionally create test targets

- include/uvwasi.h
- test/test-environ-get.c
This allows users pass arrays of C string literals.
> Make argv and envp options const

- src/path_resolver.c
- test/test-path-resolution.c
The code in `path_resolver.c` that replaces forward slashes with
backslashes on Windows did not work. It modified a chunk of
memory immediately following the memory it was meant to update.
This was leading to crashes on Windows in the Node.js test
suite ~1-2% of the time. This commit resets the pointer to the
correct location for the calculations.
Side note: this logic was broken and the slashes weren't actually
being updated, but the tests were still passing on Windows. This
logic might not really be needed after all?
Node.js stress test (4,000 runs spread across 4 windows machines): https://ci.nodejs.org/view/Stress/job/node-stress-single-test/73/ ✔️ 
Also resolves: https://github.com/nodejs/node/pull/33403
> reset pointer to prevent memory corruption

- include/wasi_serdes.h
- src/wasi_serdes.c
- test/test-serdes.c
- The bounds checking macros are converted to functions, and work in terms of sizes instead of data types.
- `iovec_t` and `ciovec_t` support is added.
Fixes: https://github.com/cjihrig/uvwasi/issues/69
Tested with these changes made in Node.js - https://ci.nodejs.org/job/node-test-commit/38386/
> updates to serdes APIs

- include/uvwasi.h
This allows C strings to be assigned.
> Use const char* in uvwasi_preopen_s

- src/debug.h
- src/uvwasi.c
Also, avoid redefining __STDC_FORMAT_MACROS.  In wabt this is defined
on the command line.
> Fix UVWASI_DEBUG_LOG after size_t change

- src/uvwasi.c
- test/test-basic-file-io.c
If uvwasi_path_filestat_get the pathname is resolved by
uvwasi__resolve_path which honors the UVWASI_LOOKUP_SYMLINK_FOLLOW
flag.
Later we were we unconditionally calling  uv_fs_stat which always
follows symlinks.  Instead we want to unconditionally call uv_fs_lstat
which never follows them (since the resolution was already handled
by the preceding call to uvwasi__resolve_path).
> Fix handling of UVWASI_LOOKUP_SYMLINK_FOLLOW in uvwasi_path_filestat_get

- include/uvwasi.h
- src/uvwasi.c
- test/test-args-get.c
- test/test-basic-file-io.c
- test/test-ebadf-input-validation.c
- test/test-environ-get.c
- test/test-fd-prestat-dir-name.c
- test/test-multiple-wasi-destroys.c
- test/test-path-create-remove-directory.c
- test/test-path-resolution.c
- test/test-random-get.c
This commit adds a convenience function, `uvwasi_options_init()`, to initialize `uvwasi_options_t` structs to default values.
Refs: https://github.com/cjihrig/uvwasi/pull/140#discussion_r429555587
> add uvwasi_options_init()

- CMakeLists.txt
- src/poll_oneoff.c
- test/test-poll-state-cleanup.c
This PR resolves an ASAN error in `poll_oneoff()`. It also includes the libuv 1.38.0 update in a separate commit.
> fix poll_oneoff ASAN error

- src/uvwasi.c
- test/test-filestat-set-times.c
This commit adds actual implementations for `uvwasi_fd_filestat_set_times()` and `uvwasi_path_filestat_set_times()`, as well as tests.
I wrote up a simple test and ran it through [Node.js as well](https://ci.nodejs.org/job/node-test-commit/38530/), and it seemed fine minus come CI infra hiccups.
> implement filestat_set_times() functions

- src/debug.h
- src/uvwasi.c
This commit renames the DEBUG() macro to prevent name collisions.
Fixes: https://github.com/cjihrig/uvwasi/issues/142
> rename DEBUG() macro to UVWASI_DEBUG()

- .github/workflows/CI.yml
This commit adds build flags to CMake to enable all warnings and to turn
warnings into errors.
> build: add -Wall -Werror to CI build

- include/wasi_serdes.h
This commit removes a macro, and fixes compilation errors on certain platforms such as NetBSD 8.2.
Refs: https://github.com/nodejs/node/issues/34510
Fixes: https://github.com/cjihrig/uvwasi/issues/145
> serdes: fix compilation errors on NetBSD 8.2

- CMakeLists.txt
Currently, the summary when configuring the build with cmake look like
this:
```console
-- summary of build options:
Install prefix:  /usr/local
Target system:   Linux
Compiler:
C compiler:    /usr/lib64/ccache/cc
CFLAGS:         -Wmaybe-uninitialized -O3
-- summary of build options:
Install prefix:  /usr/local
Target system:   Linux
Compiler:
C compiler:    /usr/lib64/ccache/cc
CFLAGS:         -Wmaybe-uninitialized -O3
Libuv version:   v1.38.1
Libuv lib:       /wasm/uvwasi/build/_deps/libuv-build
-- Configuring done
-- Generating done
-- Build files have been written to: /wasm/uvwasi/build
```
The first summary is from libuv and the second is from this project.
This commit suggest adding uvwasi to the second to make it clear which
properties belong to which project(at first I though that …
> build: add uvwasi to build summary

- src/uvwasi.c
This commit initializes timer_userdata to avoid a maybe-uninitialized
warning in uvwasi_poll_oneoff.
This warning can be seen when building using the following flags (and
also shows up in Node.js build):
```console
$ cd build
$ cmake .. -DCMAKE_C_FLAGS="-Wmaybe-uninitialized -O3"
$ make -j8
...
/wasm/uvwasi/src/uvwasi.c: In function ‘uvwasi_poll_oneoff’:
/wasm/uvwasi/src/uvwasi.c:2407:21: warning:
‘timer_userdata’ may be used uninitialized in this function [-Wmaybe-uninitialized]
2407 |     event->userdata = timer_userdata;
|     ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
```
> src: suppress maybe-uninitialized timer_userdata

- README.md
The current link to the snapshot returns a 404. A permalink to the old document is [here](https://github.com/WebAssembly/WASI/blob/17f33a538161bcf4476ea9eae53cdcf7dbd96c35/phases/snapshot/docs/wasi_unstable_preview1.md). I've updated the README to point to the new location of the WASI snapshot 1. Thanks!
> Update link to WASI snapshot 1

- include/wasi_serdes.h
- src/uvwasi.c
- src/wasi_serdes.c
- test/test-ebadf-input-validation.c
- test/test-fd-readdir.c
This commit updates the uvwasi_fd_readdir() implementation
to work, including a regression test. The function is not
supported on Windows and Android yet.
Fixes: https://github.com/cjihrig/uvwasi/issues/148
Fixes: https://github.com/cjihrig/uvwasi/issues/137
> src: improve uvwasi_fd_readdir() implementation

- include/uvwasi.h
- src/fd_table.c
- src/fd_table.h
- src/uvwasi.c
It is a minor change, but this simplifies calling `uwasi_init`.
I have not seen a real reason why this would need to be non-const as nothing is modified.
> Make options const for uvwasi_init

- README.md
- include/wasi_types.h
The URL in `README.md` is usually not visible as plaintext, but the reference in the header file is.
Refs: https://github.com/WebAssembly/WASI/issues/290
> Change remote WASI branch as per WASI SG decision

- .github/workflows/Android.yml
Yarn signature changes result in old image `apt update` will fail.
> chore: update CI Image

- src/uvwasi.c
- test/test-wasi-destroy-without-init.c
`uvwasi_destroy` currently handles the case when NULL is passed as `uvwasi`
https://github.com/nodejs/uvwasi/blob/adda15515cbb5a478d0ddb85602d987278a43384/src/uvwasi.c#L372-L373
and also when `uvwasi->fds` is NULL
https://github.com/nodejs/uvwasi/blob/adda15515cbb5a478d0ddb85602d987278a43384/src/fd_table.c#L231-L232
but not the case when `uvwasi->allocator` is NULL.
I suggest for consistency to handle fully zeroed-out `uvwasi` passed to `uvwasi_destroy`. That would simplify client-side in that you wouldn't need to check whether `uvwasi_init` finished successfully when you call `uvwasi_destroy`.
P.S. Not sure if it would also make sense to add `uvwasi->allocator = NULL;` to `uvwasi_destroy`.
> Handle NULL pointers in uvwasi_destroy consistently

- src/debug.h
This commit updates the UVWASI_DEBUG macro to accept a single format argument, one without any format specifiers in it and hence no following arguments. For example:
```c
UVWASI_DEBUG("some log message...\n");
```
This will currently result in the following compiler error:
```console
/uvwasi/src/uvwasi.c: In function ‘uvwasi_fd_readdir’: /uvwasi/src/debug.h:10:42: error:
expected expression before ‘)’ token
10 |     do { fprintf(stderr, fmt, __VA_ARGS__); } while (0)
|                                          ^
/uvwasi/src/uvwasi.c:1303:3: note: in expansion of macro ‘UVWASI_DEBUG’
1303 |   UVWASI_DEBUG("some log message...\n");
```
This change in this commit allows the above kind of log statements.
> Add support for single argument UVWASI_DEBUG

- .github/workflows/CI.yml
- CMakeLists.txt
v1.40.0 came out July 19, 2021. It's now Dec. 2022.
> build: update libuv version

- src/uv_mapping.c
When uvwasi is used on Windows, it might be used in non-"ConsoleMode" and the `uv_guess_handle` function can return two different values for `FILE_TYPE_CHAR` because of that difference, see https://github.com/libuv/libuv/blob/v1.x/src/win/handle.c#L42-L47
This function can also return `UV_FILE` in the case of `FILE_TYPE_DISK` but I assume that a disk file will properly stat and there isn't a good way to figure out which one is being returned.
This fixes #157 (took me about a month of debugging)
> fix: libuv can return UV_FILE or UV_TTY for FILE_TYPE_CHAR handles

- src/clocks.c
This PR is rebased on #181.
This increases the precision of the `UVWASI_CLOCK_PROCESS_CPUTIME_ID` and `UVWASI_CLOCK_THREAD_CPUTIME_ID` clocks on Windows. The raw values from `GetProcessTimes` and `GetThreadTimes` are in units of 100 nanoseconds, which matches the reported resolution returned from `uvwasi_clock_time_get`.
I can't find any documentation on it, but in my testing I only saw an actual precision of about 1000 nanoseconds, which I suppose makes sense if the process/thread times are counted as microseconds.
> Increase precision of clocks in clock_time_get on Windows

- include/uvwasi.h
- include/wasi_types.h
- src/uvwasi.c
- src/wasi_rights.h
- test/test-enotsup-apis.c
add the stub for sock_accept so that we have
stubs for all method in the current version of
snapshot 1. sock_accept was added later after
snapshot 1 was first documented.
Signed-off-by: Michael Dawson <mdawson@devrus.com>
> add stub for sock_accept

- README.md
Fixes up the link - missed the underline in the editor.
> docs: fixup link

- src/uvwasi.c
- test/test-fd-prestat-dir-name.c
Previously, `fd_prestat_get` would return the length of the directory name + 1, for the null terminator. This isn't quite right, as WASI strings are not null-terminated, and instead always operate in terms of a pointer and a size.
If a consumer of `fd_prestat_get` with `fd_prestat_dir_name` wants this value as a null-terminated string, they need to null-terminate it themselves, which I reflected in the tests.
This probably hasn't been noticed before because if the consumer of uvwasi uses null-terminated strings, functions like `strlen` will still report the correct value, but this isn't the case for languages that don't null-terminate strings, with null being a valid string character.
This could be considered a breaking fix if someone relied on uvwasi reporting and subsequently copying …
> fix: Return correct length of string in fd_prestat_get

- src/uv_mapping.c
Needed now that `libuv` is setting the mode correctly for named pipes.
Refs: https://github.com/libuv/libuv/pull/3811
> win: add S_ISFIFO macro

- .gitignore
- CMakeLists.txt
- README.md
- cmake/Config.cmake.in
- cmake/FindLibUV.cmake
- cmake/uvwasi.pc.in
This reworks the cmake build of the project to add install targets for uvwasi. This will make it possible for pkg-config or cmake build pipelines to discover globally installed uvwasi.
To install uvwasi, you'd run `cmake --install out` after you build.
I also removed the `WITH_SYSTEM_LIBUV` option because we should be using the globally installed libuv if it can be found. If people are very against this change, I can introduce a flag to *disable* this behavior.
I've tested this against a local branch of wasm-micro-runtime and it seems to be working. My plan is to add that build to CI once they accept my changes.
Closes #199
> feat!: Allow project to be installable

- src/uvwasi.c
Fix a minor extra semicolon warning.
I found this updating Electron's Node.js roll, since Electron builds Node.js with `-Werror,-Wextra-semi` :smile_cat:
> fix: small -Wextra-semi warning in uvwasi.c

- test/test-args-get.c
- test/test-basic-file-io.c
- test/test-clock-time-get.c
- test/test-common.h
- test/test-ebadf-input-validation.c
- test/test-einval-input-validation.c
- test/test-enotsup-apis.c
- test/test-environ-get.c
- test/test-err-to-string.c
- test/test-fd-prestat-dir-name.c
- test/test-fd-readdir-ls.c
- test/test-fd-readdir.c
- test/test-filestat-set-times.c
- test/test-multiple-wasi-destroys.c
- test/test-path-create-remove-directory.c
- test/test-path-resolution.c
- test/test-poll-state-cleanup.c
- test/test-proc-exit.c
- test/test-random-get.c
- test/test-serdes.c
- test/test-uv-mapping.c
- test/test-wasi-destroy-without-init.c
- fix intermittent failure in test-clock-time-get.
- avoid window popups that cause any failed test to just hang until test times out
> test: fixup windows tests

- src/uvwasi.c
- test/test-symlink.c
Currently the `old_path_len` argument is ignored in the implementation of `path_symlink` and the call to `uv_fs_symlink` uses the original null-terminated `old_path`, which differs to how the `path_len` arguments in other functions are treated.
This PR truncates the "old path" passed to libuv down to the length passed into `old_path_len`.
> fix: use old_path_len argument in symlink creation

- src/path_resolver.c
- test/test-path-resolution.c
This fixes https://github.com/nodejs/node/issues/49107 (relative paths in symlinks resolved incorrectly).
When following a symbolic link that points to a target using a relative path, the `uvwasi__resolve_path()` function resolves and normalizes the link's target as a relative path starting from `fd->real_path`. This should be treated as a relative path starting from the parent directory of the symbolic link.
For example, given the directory structure below:
```
.
├── source_file
└── dir
└── link -> ../source_file
```
When `fd->real_path` is `.`, the link target for link is resolved as `../source_file`, not `./source_file`. As a result, this resolution ends with an `ENOTCAPABLE` error.
> fix: resolving relative paths in symlinks

- src/uvwasi.c
- test/test-fstflags-validate.c
This commit adds a check to the validator macro for `fstflags` to return `inval` if the caller requests both `atim` and `atim_now` or both `mtim` and `mtim_now` because the request is ambiguous.  This behavior is consistent across other runtimes (WasmEdge, Wasmtime, WAMR).
> Error on ambiguous fstflags

- src/uvwasi.c
- test/test-fd-advise-dir.c
This commit adds a check to `fd_advise`.  If the fd is a directory, return `ebadf`.  This brings uvwasi in line with Wasmtime's behavior. WASI folks have [stated](https://github.com/bytecodealliance/wasmtime/issues/6505#issuecomment-1574122949) that fd_advise should not work on directories as this is a Linux-specific behavior.
> Forbid fd_advise on directories

- src/uvwasi.c
Refs https://github.com/electron/electron/pull/40675/files#diff-8df91bd501edd943197bf16d478ebd9b4be08f7b0ea13de788da961d4315febe
Fixes a `-Wshadow` compilation error hit by Electron when upgrading to Node.js v20.10.0
> chore: fix -Wshadow error in uvwasi.c

- src/uvwasi.c
- test/test-fd-pwrite-large-offset.c
This commit fixes a potential overflow in fd_pwrite.  Since `uv_fs_write` takes an `int64_t` as the offset while `fd_pwrite` accepts an `uint64_t`, we need to check it doesn't overflow when cast.
> Check offset overflow in fd_pwrite

- src/uvwasi.c
- test/test-fd-pread-large-offset.c
This commit inserts a bounds check in `fd_pread` for the `offset` parameter.  This is necessary because an implicit unsigned-to-signed integer conversion is performed when `uv_fs_read` is called.  Such a conversion results in implementation-defined behavior.  One such behavior is the offset wrapping.
fixes #257
> Prevent offset wrapping in `fd_pread`

- src/uvwasi.c
- test/test-fd-read-empty.c
This commit inserts a special case to `fd_{read,write,pread,pwrite}` such that passing in an empty list of buffers results in a no-op.  This behavior is consistent with Linux host as well as other Wasm runtimes.
fixes #260
> No-op instead of error on empty read/write

- src/path_resolver.c
- test/test-basic-file-io.c
- test/test-path-open-malformed-path.c
This commit adds a check when resolving path such that any null bytes in the input path causes errno `inval`.  This is consistent with other runtimes like Wasmtime, Wasmer, Wazero, WasmEdge, and WAMR.
fixes #265
> Disallow malformed path with null byte

- src/path_resolver.c
- src/uvwasi.c
- test/test-path-open-trailing-slash.c
- test/test-path-resolution.c
This commit fixes the behavior of `path_open` such that if the path contains trailing slashes and the target file is not a directory, the call errors. This behavior is consistent with Linux host, Wasmtime, WAMR, and WasmEdge.
fixes #267
> Preserve trailing slash in file path where it makes sense

- src/uvwasi.c
- test/test-path-symlink-absolute-path.c
This commit adds an absolute path check to `path_symlink`. This behavior is specified by [WASI][1].
[1]: https://github.com/WebAssembly/wasi-filesystem/blob/main/path-resolution.md#symlinks
fixes #271
> Error if creating symlink to absolute path

- .clusterfuzzlite/Dockerfile
- .clusterfuzzlite/build.sh
- .clusterfuzzlite/fuzz_normalize_path.c
- .clusterfuzzlite/project.yaml
- .github/workflows/cflite.yml
- README.md
- src/path_resolver.c
Resolving: https://github.com/nodejs/uvwasi/issues/251#issuecomment-2316124889
I also added a  [ClusterFuzzLite](https://google.github.io/clusterfuzzlite/) integration with the harness described in the issue.
The harness will be run when PRs are made against uvwasi.
To run the harness manually locally:
```sh
git clone https://github.com/google/oss-fuzz
git clone https://github.com/DavidKorczynski/uvwasi
cd uvwasi
git checkout enable-cflite
python3 ../oss-fuzz/infra/helper.py build_fuzzers --external $PWD
python3 ../oss-fuzz/infra/helper.py run_fuzzer --external $PWD fuzz_normalize_path -- -max_total_time=10
```
Fixes: https://github.com/nodejs/uvwasi/issues/251
> Add cflite and document normalize path

- src/uvwasi.c
In uvwasi_sock_accept() function uvwasi_malloc() can return NULL, need to check before dereference.
> Check result of uvwasi_malloc for NULL

- src/uvwasi.c
- test/test-symlink-outbox.c
- add test-symlink-outbox
---
fix #299
> Resolve old_path in uvwasi_path_symlink()

- .github/workflows/Android.yml
- .github/workflows/CI.yml
- .github/workflows/Coverage.yml
Last release to checkout v3 is more than three years old.
> chore: update checkout action version to v5
